// The Instant Quote walkthrough, written down once so the homepage explainer
// and the /instant-quote/ landing page can never disagree about which asset is
// live — the same reason SITE_URL and QUOTE_URL live in site.mjs.
//
// To publish a real screen recording: drop the file in public/ (H.264 MP4,
// muted, a minute at most) and set QUOTE_VIDEO to its absolute path, e.g.
// '/instant-quote.mp4'. Both pages swap their animated mock for the recording
// on the next build. Left null, the mock renders: nothing to host, no extra
// bytes, and it still shows the before/after the buyer came to see.
export const QUOTE_VIDEO = null;

// The still frame — the video's poster, and this page's share card. 1200x676,
// committed at public/instant-quote-preview.png. Its animated twin,
// public/instant-quote-preview.gif, is for the launch email only: mail has to
// carry absolute URLs, so it is written out in marketing/instant-quote-launch/
// rather than imported from here. Both are generated by build-preview.mjs
// beside that email.
export const QUOTE_VIDEO_POSTER = '/instant-quote-preview.png';

// Landing page the email image points at. One path, written down once, so the
// email, the sitemap and the internal links cannot drift apart.
export const QUOTE_LANDING_PATH = '/instant-quote/';
