#!/bin/bash
# PreToolUse hook: block direct edits to generated/secret files.
#
# - src/data/offers-snapshot.json is generated by `npm run sync-offers`; a hand
#   edit would be silently reverted by the next scheduled catalogue refresh.
# - .env holds the Airtable token and must never be touched by tooling
#   (.env.example remains editable).
#
# Exit 2 blocks the tool call and surfaces the message to Claude.
set -uo pipefail

file_path=$(node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{console.log(JSON.parse(d).tool_input?.file_path??"")}catch{console.log("")}})')

case "$file_path" in
  *src/data/offers-snapshot.json)
    echo "Blocked: offers-snapshot.json is generated. Refresh it with 'npm run sync-offers' (needs AIRTABLE_TOKEN); hand edits are reverted by the scheduled refresh workflow." >&2
    exit 2
    ;;
esac

base=$(basename "$file_path")
if { [ "$base" = ".env" ] || [[ "$base" == .env.* ]]; } && [ "$base" != ".env.example" ]; then
  echo "Blocked: .env files hold secrets (Airtable token) and must not be edited by tooling. Update .env.example instead if documenting a new variable." >&2
  exit 2
fi

exit 0
